[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shikhar Shetty", email = "shettyshikhar99@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.1.1",
    "fastapi>=0.142.4",
    "httpx>=0.28.1",
    "pandas>=2.3.3",
    "shap>=0.48.0",
    "uvicorn[standard]>=0.54.0",
    "xgboost>=3.0.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
